name: Build C and C++

on:
  push:
    branches:
    - master

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: apt install gcc g++ make -y
    - name: build c
      run: gcc hello.c
    - name: build c++
      run: g++ hello.cpp

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: install choco cmd
      run: @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
    - name: install choco powershell
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
