name: Build C and C++

on:
  push:
    branches:
    - master

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: sudo apt install gcc g++ make -y
    - name: build
      run: sh linux.sh
    - name: artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sh windows.sh
